language: go
go:
  - "1.12"
services:
  - docker
before_install:
  - docker pull golang:1.12.7-alpine
  - docker pull k8s.gcr.io/debian-base:v1.0.0
  - docker tag k8s.gcr.io/debian-base:v1.0.0 gcr.azk8s.cn/google_containers/debian-base:v1.0.0

script:
  - make neonsan-container
