apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: node
    ver: v1.1.0
  name: csi-neonsan-node
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-attacher
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-provisioner
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-resizer
  namespace: kube-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-snapshotter
  namespace: kube-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-attacher
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.storage.k8s.io
  resources:
  - csinodeinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      app: csi-neonsan
  - matchLabels:
      role: controller
  - matchLabels:
      csi: v1.1.0
  - matchLabels:
      owner: yunify
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-controller
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: node
    ver: v1.1.0
  name: csi-neonsan-node
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-provisioner
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-resizer
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-snapshotter
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots/status
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - watch
  - delete
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-attacher
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-neonsan-attacher
subjects:
- kind: ServiceAccount
  name: csi-neonsan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-provsioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-neonsan-provisioner
subjects:
- kind: ServiceAccount
  name: csi-neonsan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-resizer
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-neonsan-resizer
subjects:
- kind: ServiceAccount
  name: csi-resizer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-snapshotter
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-neonsan-snapshotter
subjects:
- kind: ServiceAccount
  name: csi-snapshotter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: controller
    ver: v1.1.0
  name: csi-neonsan-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-neonsan-controller
subjects:
- kind: ServiceAccount
  name: csi-neonsan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: node
    ver: v1.1.0
  name: csi-neonsan-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-neonsan-node
subjects:
- kind: ServiceAccount
  name: csi-neonsan-node
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    ver: v1.1.0
  name: csi-neonsan-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-neonsan
      owner: yunify
      role: controller
      ver: v1.1.0
  template:
    metadata:
      labels:
        app: csi-neonsan
        owner: yunify
        role: controller
        ver: v1.1.0
    spec:
      containers:
      - args:
        - --csi-address=$(ADDRESS)
        - --enable-leader-election
        - --feature-gates=Topology=true
        - --leader-election-type=leases
        - --retry-interval-max=5m
        - --retry-interval-start=5s
        - --timeout=90s
        - --worker-threads=5
        - --volume-name-prefix=pvc
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.azk8s.cn/k8scsi/csi-provisioner:v1.4.0-rc1
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --leader-election
        - --retry-interval-max=5m
        - --retry-interval-start=5s
        - --timeout=90s
        - --worker-threads=5
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.azk8s.cn/k8scsi/csi-attacher:v2.0.0
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --leader-election
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.azk8s.cn/k8scsi/csi-resizer:v0.2.0
        imagePullPolicy: IfNotPresent
        name: csi-resizer
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --config=/etc/neonsan/qbd.conf
        - --drivername=neonsan.csi.qingcloud.com
        - --endpoint=$(CSI_ENDPOINT)
        - --maxvolume=10
        - --nodeid=$(NODE_ID)
        - --poolname=kube
        - --v=5
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://csi/csi.sock
        image: csiplugin/csi-neonsan:canary
        imagePullPolicy: IfNotPresent
        name: csi-neonsan
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /etc/neonsan
          name: neonsan-config
      serviceAccount: csi-neonsan-controller
      volumes:
      - emptyDir: null
        name: socket-dir
      - hostPath:
          path: /etc/neonsan
        name: neonsan-config
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    role: node
    ver: v1.1.0
  name: csi-neonsan-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-neonsan
      owner: yunify
      role: node
      ver: v1.1.0
  template:
    metadata:
      labels:
        app: csi-neonsan
        owner: yunify
        role: node
        ver: v1.1.0
    spec:
      containers:
      - args:
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=/var/lib/kubelet/plugins/neonsan.csi.qingcloud.com/csi.sock
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: quay.azk8s.cn/k8scsi/csi-node-driver-registrar:v1.2.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/neonsan.csi.qingcloud.com /registration/neonsan.csi.qingcloud.com-reg.sock
        name: node-registrar
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      hostNetwork: true
      serviceAccount: csi-neonsan-node
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: dedicated
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/neonsan.csi.qingcloud.com/
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
        name: registration-dir
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  labels:
    app: csi-neonsan
    owner: yunify
    ver: v1.1.0
  name: neonsan.csi.qingcloud.com
spec:
  attachRequired: true
  podInfoOnMount: false
